#!/usr/bin/env bash
# =============================================================================
# Handla — deploy on a VPS where Traefik already owns 80/443
# =============================================================================
# Same idea as deploy/deploy.sh, but routes Handla through the existing Traefik
# instead of Handla's own nginx+certbot. Uses an EXPLICIT compose file list so
# the auto-loaded docker-compose.override.yml (nginx/certbot) is NOT applied.
#
#   ./deploy/deploy.traefik.sh
#   PULL=0 ./deploy/deploy.traefik.sh
#   TRAEFIK_NETWORK=proxy TRAEFIK_CERTRESOLVER=letsencrypt ./deploy/deploy.traefik.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HANDLA_DIR="${HANDLA_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
BRANCH="${DEPLOY_BRANCH:-main}"
PULL="${PULL:-1}"
export TRAEFIK_NETWORK="${TRAEFIK_NETWORK:-proxy}"
export TRAEFIK_CERTRESOLVER="${TRAEFIK_CERTRESOLVER:-letsencrypt}"
export TRAEFIK_ENTRYPOINT="${TRAEFIK_ENTRYPOINT:-websecure}"
# Explicit list => Compose does NOT auto-load docker-compose.override.yml.
COMPOSE_FILES="-f docker-compose.yml -f deploy/docker-compose.traefik.yml"

log() { echo "[deploy-traefik] $*"; }

cd "$HANDLA_DIR"

if [ "$PULL" = "1" ] && [ -d .git ]; then
  log "Fetching latest '$BRANCH'..."
  git fetch --all --prune
  git checkout "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  log "Skipping git pull (PULL=$PULL or no .git); deploying current working tree."
fi

log "Verifying backend .env exists..."
if [ ! -f handla-backend/.env ]; then
  echo "[deploy-traefik] ERROR: handla-backend/.env is missing on the VPS." >&2
  exit 1
fi

# Root ./.env for Compose ${VAR} interpolation (mysql creds, api port).
log "Generating root ./.env for Docker Compose interpolation..."
get() { grep -E "^$1=" handla-backend/.env | tail -n1 | cut -d= -f2- || true; }
{
  echo "# AUTO-GENERATED by deploy/deploy.traefik.sh from handla-backend/.env"
  echo "PORT=$(get PORT)"
  echo "DATABASE_NAME=$(get DATABASE_NAME)"
  echo "DATABASE_USER=$(get DATABASE_USER)"
  echo "DATABASE_PASSWORD=$(get DATABASE_PASSWORD)"
  echo "DATABASE_ROOT_PASSWORD=$(get DATABASE_ROOT_PASSWORD)"
  echo "DATABASE_SYNCHRONIZE=$(get DATABASE_SYNCHRONIZE)"
  echo "REDIS_USERNAME=$(get REDIS_USERNAME)"
  echo "REDIS_PASSWORD=$(get REDIS_PASSWORD)"
} > .env
# Default the Redis application username if it was not set in the backend .env.
grep -q '^REDIS_USERNAME=.\+'       .env || sed -i 's|^REDIS_USERNAME=.*|REDIS_USERNAME=handla_app|' .env
grep -q '^PORT=.\+'                  .env || sed -i 's|^PORT=.*|PORT=3001|'                            .env
grep -q '^DATABASE_NAME=.\+'         .env || sed -i 's|^DATABASE_NAME=.*|DATABASE_NAME=handla_db|'       .env
grep -q '^DATABASE_USER=.\+'         .env || sed -i 's|^DATABASE_USER=.*|DATABASE_USER=handla|'          .env
grep -q '^DATABASE_SYNCHRONIZE=.\+'  .env || sed -i 's|^DATABASE_SYNCHRONIZE=.*|DATABASE_SYNCHRONIZE=false|' .env
chmod 600 .env

# Remove any leftover Handla nginx/certbot containers from a prior override run.
log "Removing Handla's own nginx/certbot if present (Traefik handles TLS)..."
docker rm -f handla_nginx handla_certbot >/dev/null 2>&1 || true

log "Verifying Traefik external network '${TRAEFIK_NETWORK}' exists..."
if ! docker network inspect "${TRAEFIK_NETWORK}" >/dev/null 2>&1; then
  echo "[deploy-traefik] ERROR: external network '${TRAEFIK_NETWORK}' not found." >&2
  echo "[deploy-traefik]        Set TRAEFIK_NETWORK to your Traefik network name." >&2
  exit 1
fi

log "Building images..."
docker compose $COMPOSE_FILES build

# Recreate the stack in place (no full `down`) to avoid a network race.
#
# Why: an interrupted previous `up -d` can leave a half-renamed container
# behind (e.g. "53532e2b81e8_handla_api") that still holds the "handla_api"
# name. A stale name then makes the next `up` fail with:
#   Conflict. The container name "/handla_mysql" is already in use…
#
# We previously did `down --remove-orphans` then `up`. But `down` DELETES the
# compose network, and `up` immediately recreates it — occasionally the network
# teardown/recreate races with container creation and `up` conflicts with a
# container it just created in the SAME invocation. To avoid that race we:
#   1. force-remove the known fixed-name containers up front (clears stale
#      names WITHOUT tearing the network down), and
#   2. use `up -d --remove-orphans --force-recreate`, which recreates the
#      service containers in place and keeps the network stable, and
#   3. retry ONCE if a transient name Conflict still slips through (belt &
#      braces), force-removing the fixed names again before the retry.
#
# A few seconds of downtime here is acceptable for a deploy step and is far
# preferable to a wedged, half-updated stack.
FIXED_NAMES="handla_api handla_web handla_mysql handla_redis"

log "Force-removing any stale fixed-name containers (keeps the network up)..."
# shellcheck disable=SC2086
docker rm -f $FIXED_NAMES >/dev/null 2>&1 || true

bring_up() {
  # shellcheck disable=SC2086
  docker compose $COMPOSE_FILES up -d --remove-orphans --force-recreate
}

log "Starting/updating the stack (routed via Traefik)..."
if ! bring_up; then
  log "First 'up' failed (likely a transient container-name Conflict). Clearing and retrying once..."
  # shellcheck disable=SC2086
  docker rm -f $FIXED_NAMES >/dev/null 2>&1 || true
  sleep 3
  bring_up
fi

log "Pruning dangling images..."
docker image prune -f >/dev/null 2>&1 || true

log "Current status:"
docker compose $COMPOSE_FILES ps

log "Done ✓  Traefik will issue/serve TLS for handla.tech, www, api via '${TRAEFIK_CERTRESOLVER}'."
