#!/usr/bin/env bash
# =============================================================================
# Handla — VPS deploy script (invoked by GitHub Actions over SSH, the Genspark
# "Bring your own SSH server" tool, or manually).
#
# Idempotent: pulls the latest branch, regenerates the root ./.env that Docker
# Compose needs for ${VAR} interpolation, rebuilds changed images, and restarts
# the FULL production stack (mysql · redis · api · web · nginx · certbot).
# The api entrypoint runs TypeORM migrations automatically on boot.
#
# Assumes:
#   - repo present at $HANDLA_DIR (default: the repo this script lives in)
#   - handla-backend/.env present on the VPS (holds all secrets; NOT in git)
#   - Docker + Docker Compose v2 installed
# =============================================================================
set -euo pipefail

# Resolve the repo root: prefer $HANDLA_DIR, else the git root of this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HANDLA_DIR="${HANDLA_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
BRANCH="${DEPLOY_BRANCH:-main}"
# Set PULL=0 to skip the git fetch/reset (useful when the deploy tool already
# uploaded/updated the working tree itself).
PULL="${PULL:-1}"
# No -f flags: Compose auto-loads docker-compose.yml + docker-compose.override.yml
# (the production overlay). This is the SAME command an automated SSH deploy
# tool runs by default, so both paths bring up the identical full stack.
COMPOSE_FILES=""

log() { echo "[deploy] $*"; }

cd "$HANDLA_DIR"

if [ "$PULL" = "1" ] && [ -d .git ]; then
  log "Fetching latest '$BRANCH'..."
  git fetch --all --prune
  git checkout "$BRANCH"
  git reset --hard "origin/$BRANCH"
else
  log "Skipping git pull (PULL=$PULL or no .git); deploying current working tree."
fi

log "Verifying backend .env exists..."
if [ ! -f handla-backend/.env ]; then
  echo "[deploy] ERROR: handla-backend/.env is missing on the VPS." >&2
  echo "[deploy]        Create it from handla-backend/.env.production.example." >&2
  exit 1
fi

# ── Generate the root ./.env that Compose uses for ${VAR} interpolation ──────
# Compose interpolates ${DATABASE_PASSWORD} etc. from the repo-root ./.env, NOT
# from a service's env_file. We derive it from handla-backend/.env so there is a
# single source of truth and no drift between the two files.
log "Generating root ./.env for Docker Compose interpolation..."
get() { grep -E "^$1=" handla-backend/.env | tail -n1 | cut -d= -f2- || true; }
{
  echo "# AUTO-GENERATED by deploy/deploy.sh from handla-backend/.env — do not edit."
  echo "PORT=$(get PORT)"
  echo "DATABASE_NAME=$(get DATABASE_NAME)"
  echo "DATABASE_USER=$(get DATABASE_USER)"
  echo "DATABASE_PASSWORD=$(get DATABASE_PASSWORD)"
  echo "DATABASE_ROOT_PASSWORD=$(get DATABASE_ROOT_PASSWORD)"
  echo "DATABASE_SYNCHRONIZE=$(get DATABASE_SYNCHRONIZE)"
  echo "DATABASE_MIGRATION_USER=$(get DATABASE_MIGRATION_USER)"
  echo "DATABASE_MIGRATION_PASSWORD=$(get DATABASE_MIGRATION_PASSWORD)"
} > .env
# Fill sensible defaults if any were blank in the backend .env.
grep -q '^PORT=.\+'                  .env || sed -i 's|^PORT=.*|PORT=3001|'                    .env
grep -q '^DATABASE_NAME=.\+'         .env || sed -i 's|^DATABASE_NAME=.*|DATABASE_NAME=handla_db|' .env
# Runtime DB identity is required: never silently fall back to the deprecated
# privileged legacy `handla` user. Fail clearly on a missing/empty secret.
grep -q '^DATABASE_USER=.\+'         .env || { echo "FATAL: DATABASE_USER missing from handla-backend/.env (canonical: handla_runtime). Refusing to deploy with a legacy/empty DB identity." >&2; exit 5; }
grep -q '^DATABASE_SYNCHRONIZE=.\+'  .env || sed -i 's|^DATABASE_SYNCHRONIZE=.*|DATABASE_SYNCHRONIZE=false|' .env
chmod 600 .env

log "Building images (only changed layers rebuild)..."
docker compose ${COMPOSE_FILES} build

log "Starting/updating the stack..."
docker compose ${COMPOSE_FILES} up -d

log "Pruning dangling images to reclaim disk..."
docker image prune -f >/dev/null 2>&1 || true

log "Current status:"
docker compose ${COMPOSE_FILES} ps

log "Done ✓  (api migrations run automatically via the api entrypoint)"
