import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
  Index,
} from 'typeorm';
import { InvoicePaymentStatus } from '../../../common/enums';
import { Client } from '../../clients/entities/client.entity';
import { User } from '../../auth/entities/user.entity';
import { InvoiceLineItem } from './invoice-line-item.entity';

/**
 * ERP-7 — Invoice entity.
 *
 * An Invoice is tied to a Client (CASCADE on delete).
 * Owner is the EMPLOYEE who created/manages it (SET NULL on delete).
 *
 * Status flow:
 *   UNPAID → PAID    (via markAsPaid — EMPLOYEE/ADMIN)
 *   UNPAID → OVERDUE (auto, via recalculateOverdueStatus scheduler — 1am daily)
 *   OVERDUE → PAID   (via markAsPaid)
 *
 * Financial precision:
 *   All monetary fields use NUMERIC(12,2) to avoid float rounding.
 *   Calculations are done in JS with toFixed(2) rounding before storage.
 *
 * Invoice number format: INV-YYYY-NNNN (e.g. INV-2026-0001)
 * Generated by InvoicesService.generateInvoiceNumber() using SELECT FOR UPDATE
 * to ensure thread-safety.
 */
@Entity('invoices')
export class Invoice {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  // ─── Invoice number (unique) ───────────────────────────────────────────────
  @Column({ name: 'invoice_number', type: 'varchar', length: 50, unique: true })
  invoiceNumber: string;

  // ─── FK: Client (CASCADE) ─────────────────────────────────────────────────
  @Column({ name: 'client_id', type: 'varchar', length: 36 })
  @Index('idx_invoices_client_id')
  clientId: string;

  @ManyToOne(() => Client, { onDelete: 'CASCADE', nullable: false, eager: false })
  @JoinColumn({ name: 'client_id' })
  client: Client;

  // ─── FK: Owner EMPLOYEE (SET NULL) ────────────────────────────────────────
  @Column({ name: 'owner_id', type: 'varchar', length: 36, nullable: true })
  @Index('idx_invoices_owner_id')
  ownerId: string | null;

  @ManyToOne(() => User, { onDelete: 'SET NULL', nullable: true, eager: false })
  @JoinColumn({ name: 'owner_id' })
  owner: User | null;

  // ─── Financial fields ─────────────────────────────────────────────────────
  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  subtotal: number;

  @Column({ name: 'tax_rate', type: 'decimal', precision: 5, scale: 2, default: 0 })
  taxRate: number;

  @Column({ name: 'tax_amount', type: 'decimal', precision: 12, scale: 2, default: 0 })
  taxAmount: number;

  @Column({ type: 'decimal', precision: 12, scale: 2, default: 0 })
  total: number;

  @Column({ type: 'varchar', length: 3, default: 'USD' })
  currency: string;

  // ─── Payment status ───────────────────────────────────────────────────────
  @Column({
    name: 'payment_status',
    type: 'enum',
    enum: InvoicePaymentStatus,
    default: InvoicePaymentStatus.UNPAID,
  })
  @Index('idx_invoices_payment_status')
  paymentStatus: InvoicePaymentStatus;

  // ─── Dates ────────────────────────────────────────────────────────────────
  @Column({ name: 'due_date', type: 'date', nullable: true })
  @Index('idx_invoices_due_date')
  dueDate: string | null;

  @Column({ name: 'paid_at', type: 'datetime', nullable: true })
  paidAt: Date | null;

  // ─── Notes ────────────────────────────────────────────────────────────────
  @Column({ type: 'text', nullable: true })
  notes: string | null;

  // ─── Relations ────────────────────────────────────────────────────────────
  @OneToMany(() => InvoiceLineItem, (item) => item.invoice, {
    cascade: true,
    eager: false,
  })
  lineItems: InvoiceLineItem[];

  // ─── Audit timestamps ─────────────────────────────────────────────────────
  @CreateDateColumn({ name: 'created_at', type: 'datetime' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'datetime' })
  updatedAt: Date;
}
