import type { MetadataRoute } from 'next';
import { LOCALES, DEFAULT_LOCALE, type Locale } from '@/i18n/config';
import { SERVICE_SLUGS } from '@/i18n/services-data';

/**
 * Dynamic multilingual sitemap generated by Next.js App Router (native — no
 * dependency). Served at /sitemap.xml.
 *
 * Public SEO pages are server-rendered under /[locale]/… (en|ar). Every
 * indexable route is listed once per locale, and each entry carries reciprocal
 * hreflang alternates (`alternates.languages`) pointing at the en + ar variants
 * plus x-default → the English URL. This mirrors the <link rel="alternate">
 * tags emitted in each page's <head> so the two signals agree.
 *
 * ONLY genuine, public, indexable marketing/product pages are listed. The
 * following are intentionally EXCLUDED (and additionally `noindex` via
 * metadata / robots):
 *   • Private / authenticated: /auth, /dashboard, /erp, /profile, /admin, /api
 *   • Public utility docs:     /contract/public/*, /invoice/public/*, /quotation/public/*
 *   • Legacy non-localized URLs (/, /products, /projects, …) — these 308-redirect
 *     to their /en equivalent, so only the localized targets are advertised.
 *   • Product "demo" routes (/products/*\/demo/*) — interactive view-only demos,
 *     crawlable but not promoted as primary landing pages.
 *
 * NOTE on `lastModified`: intentionally OMITTED. There is no reliable per-page
 * modification timestamp yet, and fabricating one (e.g. `new Date()`) would send
 * a fake freshness signal on every deploy. When real content timestamps exist
 * (DB `updatedAt` for products/projects) set `lastModified` per URL from that.
 */

type ChangeFreq = 'weekly' | 'monthly';

// Locale-agnostic public route templates. `sub` is appended after /{locale}.
// priority/changeFrequency reflect relative importance, not fabricated metrics.
const PUBLIC_ROUTES: Array<{ sub: string; changeFrequency: ChangeFreq; priority: number }> = [
  { sub: '',                    changeFrequency: 'weekly',  priority: 1.0 }, // home
  { sub: '/products',           changeFrequency: 'weekly',  priority: 0.9 },
  { sub: '/products/manarah',   changeFrequency: 'weekly',  priority: 0.9 },
  { sub: '/products/madar',     changeFrequency: 'weekly',  priority: 0.9 },
  { sub: '/products/matjary',   changeFrequency: 'weekly',  priority: 0.9 },
  { sub: '/projects',           changeFrequency: 'weekly',  priority: 0.8 },
  { sub: '/services',           changeFrequency: 'monthly', priority: 0.8 },
  // Genuine service landing pages (no fabricated/filler services).
  ...SERVICE_SLUGS.map((slug) => ({
    sub: `/services/${slug}` as const,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  })),
];

export default function sitemap(): MetadataRoute.Sitemap {
  // Canonical host — always https://handla.tech (no www, no http).
  const baseUrl = (process.env.NEXT_PUBLIC_APP_URL || 'https://handla.tech').replace(/\/$/, '');

  const urlFor = (locale: Locale, sub: string) => `${baseUrl}/${locale}${sub}`;

  const entries: MetadataRoute.Sitemap = [];

  for (const { sub, changeFrequency, priority } of PUBLIC_ROUTES) {
    // Reciprocal hreflang map shared by every locale variant of this route.
    const languages: Record<string, string> = {};
    for (const l of LOCALES) languages[l] = urlFor(l, sub);
    languages['x-default'] = urlFor(DEFAULT_LOCALE, sub);

    for (const locale of LOCALES) {
      entries.push({
        url: urlFor(locale, sub),
        changeFrequency,
        priority,
        alternates: { languages },
      });
    }
  }

  return entries;
}
