import type { MetadataRoute } from 'next';

/**
 * Dynamic sitemap generated by Next.js App Router (native — no dependency).
 * Served at /sitemap.xml.
 *
 * Only genuine, public, indexable marketing/product pages are listed here.
 * Private / authenticated / internal / utility routes are intentionally
 * EXCLUDED and additionally protected with `noindex` metadata:
 *   /auth, /dashboard, /admin, /erp, /profile, /api,
 *   /contract/public/*, /invoice/public/*, /quotation/public/*
 *
 * Product "demo" routes (/products/*\/demo/*) are interactive view-only
 * demos, not primary SEO landing pages, so they are not promoted here
 * (they remain crawlable, just not advertised in the sitemap).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  // Canonical host — always https://handla.tech (no www, no http).
  const baseUrl = (process.env.NEXT_PUBLIC_APP_URL || 'https://handla.tech').replace(/\/$/, '');
  const lastModified = new Date();

  const routes: Array<{ path: string; changeFrequency: 'weekly'; priority: number }> = [
    { path: '/',                  changeFrequency: 'weekly', priority: 1.0 },
    { path: '/projects',          changeFrequency: 'weekly', priority: 0.8 },
    { path: '/products',          changeFrequency: 'weekly', priority: 0.9 },
    { path: '/products/manarah',  changeFrequency: 'weekly', priority: 0.9 },
    { path: '/products/matjary',  changeFrequency: 'weekly', priority: 0.9 },
    { path: '/products/madar',    changeFrequency: 'weekly', priority: 0.9 },
  ];

  return routes.map(({ path, changeFrequency, priority }) => ({
    url:             `${baseUrl}${path}`,
    lastModified,
    changeFrequency,
    priority,
  }));
}
