import type { MetadataRoute } from 'next';

/**
 * Dynamic sitemap generated by Next.js App Router.
 * Accessible at /sitemap.xml
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://handla.tech';
  const now     = new Date();

  return [
    {
      url:              `${baseUrl}/`,
      lastModified:     now,
      changeFrequency:  'weekly',
      priority:         1,
    },
    {
      url:              `${baseUrl}/auth`,
      lastModified:     now,
      changeFrequency:  'monthly',
      priority:         0.6,
    },
  ];
}
